# Generated by Django 3.0.6 on 2020-05-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('channel', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('impressions', models.CharField(max_length=100)),
                ('clicks', models.CharField(max_length=100)),
                ('installs', models.CharField(max_length=100)),
                ('spend', models.CharField(max_length=100)),
                ('revenue', models.CharField(max_length=100)),
            ],
        ),
    ]
