# Generated by Django 3.0.4 on 2020-05-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webapp',
            name='clicks',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='impressions',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='installs',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='revenue',
            field=models.PositiveIntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='spend',
            field=models.PositiveIntegerField(max_length=100),
        ),
    ]
