# Generated by Django 3.0.4 on 2020-05-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200522_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webapp',
            options={'verbose_name': 'Webapp', 'verbose_name_plural': 'Webapp'},
        ),
        migrations.AlterField(
            model_name='webapp',
            name='clicks',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='impressions',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='installs',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='revenue',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='webapp',
            name='spend',
            field=models.PositiveIntegerField(),
        ),
    ]
